hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-store
          uri: lb://book-store
          predicates:
            - Path=/api/books/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
            - RewritePath=/api/(?<books>.*), /$\{books}
            - name: Hystrix
              args:
                name: booksFallbackCommand
                fallbackUri: forward:/fallback/books

server:
  port: 8887

jwt:
  key: dGVzdAo=

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: heapdump, loggers, prometheus, threaddump, info, metrics, health, hystrix.stream
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: always

